export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

export const SET_DASHBOARD_COUNT = "SET_DASHBOARD_COUNT";

export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const SET_USERS_LIST = "SET_USERS_LIST";
export const RESET_USER_LIST = "RESET_USER_LIST";

export const FETCH_COACH_LIST = "FETCH_COACH_LIST";
export const SET_COACHES_LIST = "SET_COACHES_LIST";
export const RESET_COACH_LIST = "RESET_COACH_LIST";

export const INITIALIZE_LOADER = "INITIALIZE_LOADER";
export const RESET_LOADING = "RESET_LOADING";
export const INITIALIZE_FORM = "INITIALIZE_FORM";
export const FORM_SUCCESS = "FORM_SUCCESS";
export const FORM_SUBMITTING = "FORM_SUBMITTING";
export const RESET_FORM_SUBMITTING = "RESET_FORM_SUBMITTING";
